package com.allen.controller;

import com.allen.model.DATA;

/**
 * Created by allen on 10/08/17.
 *
 * Generated by http://pojo.sodhanalibrary.com/Convert
 */
public class MainParser
{
    private com.allen.model.DATA[] DATA;

    public DATA[] getDATA ()
    {
        return DATA;
    }

    public void setDATA (DATA[] DATA)
    {
        this.DATA = DATA;
    }

    @Override
    public String toString()
    {
        return "ClassPojo [DATA = "+DATA+"]";
    }
}
