package com.allen.model;

/**
 * Created by allen on 10/08/17.
 *
 * Generated by http://pojo.sodhanalibrary.com/Convert
 */
public class DATA implements Comparable<DATA>{
    private String PROCESSING_ORG_TXT;

    private String MPT_EXCEEDED;

    private String SCOPING_KEY;

    private String MPT_USED;

    private String INIT_SEND;

    private String OBJECT_ID;

    private String EMPL_RESP;

    private String MESSAGE_NO;

    private String PROCESSOR;

    private String REPORTER_ID;

    private String CHANGE_DATE;

    private String MESSAGE_YEAR;

    private String IRT_FUL;

    private String ORT_PLAN_END;

    private String DESCRIPTION;

    private String IRT_STATUS;

    private String MPT_START;

    private String QUEUE_NAME;

    private String SOL_PLANNED;

    private String IRT_USED;

    private String PRIORITY_DESCR;

    private String IRT_EXPIRY;

    private String CUST_NAME;

    private String IRT_START;

    private String CREATE_DATE;

    private String SCOPING_DESCR;

    private String REPORTER_NAME;

    private String SYSTEM_ID;

    private String PROCESSING_ORG;

    private String READMARK;

    private String PROCESSOR_NAME;

    private String CONFIRMATION_DATE;

    private String ORG_LVL_TEXT;

    private String CATEGORY;

    private String PRIORITY_KEY;

    private String MPT_EXPIRY;

    private String STATUS_DESCR;

    private String INFO;

    private String MPT_STATUS;

    private String STATUS_KEY;

    private String ESCALATED;

    private String ESCALATION;

    private String ORG_LVL;

    private String PROCESS_TYPE;

    private String LAST_CHANGED_AT_SAP;

    private String INIT_RECP;

    private String SERVICE_TEAM_TEXT;

    private String MESSAGE_INSNO;

    private String CSS_OBJECT_ID;

    private String WORK_PRIO;

    private String CUST_NO;

    private String WORK_PRIO_SORT;

    private String OBJECT_GUID;

    private String ORT_ACT_END;

    private String PROCESSOR_ID;

    private String URL_MESSAGE;

    public String getPROCESSING_ORG_TXT ()
    {
        return PROCESSING_ORG_TXT;
    }

    public void setPROCESSING_ORG_TXT (String PROCESSING_ORG_TXT)
    {
        this.PROCESSING_ORG_TXT = PROCESSING_ORG_TXT;
    }

    public String getMPT_EXCEEDED ()
    {
        return MPT_EXCEEDED;
    }

    public void setMPT_EXCEEDED (String MPT_EXCEEDED)
    {
        this.MPT_EXCEEDED = MPT_EXCEEDED;
    }

    public String getSCOPING_KEY ()
    {
        return SCOPING_KEY;
    }

    public void setSCOPING_KEY (String SCOPING_KEY)
    {
        this.SCOPING_KEY = SCOPING_KEY;
    }

    public String getMPT_USED ()
    {
        return MPT_USED;
    }

    public void setMPT_USED (String MPT_USED)
    {
        this.MPT_USED = MPT_USED;
    }

    public String getINIT_SEND ()
    {
        return INIT_SEND;
    }

    public void setINIT_SEND (String INIT_SEND)
    {
        this.INIT_SEND = INIT_SEND;
    }

    public String getOBJECT_ID ()
    {
        return OBJECT_ID;
    }

    public void setOBJECT_ID (String OBJECT_ID)
    {
        this.OBJECT_ID = OBJECT_ID;
    }

    public String getEMPL_RESP ()
    {
        return EMPL_RESP;
    }

    public void setEMPL_RESP (String EMPL_RESP)
    {
        this.EMPL_RESP = EMPL_RESP;
    }

    public String getMESSAGE_NO ()
    {
        return MESSAGE_NO;
    }

    public void setMESSAGE_NO (String MESSAGE_NO)
    {
        this.MESSAGE_NO = MESSAGE_NO;
    }

    public String getPROCESSOR ()
    {
        return PROCESSOR;
    }

    public void setPROCESSOR (String PROCESSOR)
    {
        this.PROCESSOR = PROCESSOR;
    }

    public String getREPORTER_ID ()
    {
        return REPORTER_ID;
    }

    public void setREPORTER_ID (String REPORTER_ID)
    {
        this.REPORTER_ID = REPORTER_ID;
    }

    public String getCHANGE_DATE ()
    {
        return CHANGE_DATE;
    }

    public void setCHANGE_DATE (String CHANGE_DATE)
    {
        this.CHANGE_DATE = CHANGE_DATE;
    }

    public String getMESSAGE_YEAR ()
    {
        return MESSAGE_YEAR;
    }

    public void setMESSAGE_YEAR (String MESSAGE_YEAR)
    {
        this.MESSAGE_YEAR = MESSAGE_YEAR;
    }

    public String getIRT_FUL ()
    {
        return IRT_FUL;
    }

    public void setIRT_FUL (String IRT_FUL)
    {
        this.IRT_FUL = IRT_FUL;
    }

    public String getORT_PLAN_END ()
    {
        return ORT_PLAN_END;
    }

    public void setORT_PLAN_END (String ORT_PLAN_END)
    {
        this.ORT_PLAN_END = ORT_PLAN_END;
    }

    public String getDESCRIPTION ()
    {
        return DESCRIPTION;
    }

    public void setDESCRIPTION (String DESCRIPTION)
    {
        this.DESCRIPTION = DESCRIPTION;
    }

    public String getIRT_STATUS ()
    {
        return IRT_STATUS;
    }

    public void setIRT_STATUS (String IRT_STATUS)
    {
        this.IRT_STATUS = IRT_STATUS;
    }

    public String getMPT_START ()
    {
        return MPT_START;
    }

    public void setMPT_START (String MPT_START)
    {
        this.MPT_START = MPT_START;
    }

    public String getQUEUE_NAME ()
    {
        return QUEUE_NAME;
    }

    public void setQUEUE_NAME (String QUEUE_NAME)
    {
        this.QUEUE_NAME = QUEUE_NAME;
    }

    public String getSOL_PLANNED ()
    {
        return SOL_PLANNED;
    }

    public void setSOL_PLANNED (String SOL_PLANNED)
    {
        this.SOL_PLANNED = SOL_PLANNED;
    }

    public String getIRT_USED ()
    {
        return IRT_USED;
    }

    public void setIRT_USED (String IRT_USED)
    {
        this.IRT_USED = IRT_USED;
    }

    public String getPRIORITY_DESCR ()
    {
        return PRIORITY_DESCR;
    }

    public void setPRIORITY_DESCR (String PRIORITY_DESCR)
    {
        this.PRIORITY_DESCR = PRIORITY_DESCR;
    }

    public String getIRT_EXPIRY ()
    {
        return IRT_EXPIRY;
    }

    public void setIRT_EXPIRY (String IRT_EXPIRY)
    {
        this.IRT_EXPIRY = IRT_EXPIRY;
    }

    public String getCUST_NAME ()
    {
        return CUST_NAME;
    }

    public void setCUST_NAME (String CUST_NAME)
    {
        this.CUST_NAME = CUST_NAME;
    }

    public String getIRT_START ()
    {
        return IRT_START;
    }

    public void setIRT_START (String IRT_START)
    {
        this.IRT_START = IRT_START;
    }

    public String getCREATE_DATE ()
    {
        return CREATE_DATE;
    }

    public void setCREATE_DATE (String CREATE_DATE)
    {
        this.CREATE_DATE = CREATE_DATE;
    }

    public String getSCOPING_DESCR ()
    {
        return SCOPING_DESCR;
    }

    public void setSCOPING_DESCR (String SCOPING_DESCR)
    {
        this.SCOPING_DESCR = SCOPING_DESCR;
    }

    public String getREPORTER_NAME ()
    {
        return REPORTER_NAME;
    }

    public void setREPORTER_NAME (String REPORTER_NAME)
    {
        this.REPORTER_NAME = REPORTER_NAME;
    }

    public String getSYSTEM_ID ()
    {
        return SYSTEM_ID;
    }

    public void setSYSTEM_ID (String SYSTEM_ID)
    {
        this.SYSTEM_ID = SYSTEM_ID;
    }

    public String getPROCESSING_ORG ()
    {
        return PROCESSING_ORG;
    }

    public void setPROCESSING_ORG (String PROCESSING_ORG)
    {
        this.PROCESSING_ORG = PROCESSING_ORG;
    }

    public String getREADMARK ()
    {
        return READMARK;
    }

    public void setREADMARK (String READMARK)
    {
        this.READMARK = READMARK;
    }

    public String getPROCESSOR_NAME ()
    {
        return PROCESSOR_NAME;
    }

    public void setPROCESSOR_NAME (String PROCESSOR_NAME)
    {
        this.PROCESSOR_NAME = PROCESSOR_NAME;
    }

    public String getCONFIRMATION_DATE ()
    {
        return CONFIRMATION_DATE;
    }

    public void setCONFIRMATION_DATE (String CONFIRMATION_DATE)
    {
        this.CONFIRMATION_DATE = CONFIRMATION_DATE;
    }

    public String getORG_LVL_TEXT ()
    {
        return ORG_LVL_TEXT;
    }

    public void setORG_LVL_TEXT (String ORG_LVL_TEXT)
    {
        this.ORG_LVL_TEXT = ORG_LVL_TEXT;
    }

    public String getCATEGORY ()
    {
        return CATEGORY;
    }

    public void setCATEGORY (String CATEGORY)
    {
        this.CATEGORY = CATEGORY;
    }

    public String getPRIORITY_KEY ()
    {
        return PRIORITY_KEY;
    }

    public void setPRIORITY_KEY (String PRIORITY_KEY)
    {
        this.PRIORITY_KEY = PRIORITY_KEY;
    }

    public String getMPT_EXPIRY ()
    {
        return MPT_EXPIRY;
    }

    public void setMPT_EXPIRY (String MPT_EXPIRY)
    {
        this.MPT_EXPIRY = MPT_EXPIRY;
    }

    public String getSTATUS_DESCR ()
    {
        return STATUS_DESCR;
    }

    public void setSTATUS_DESCR (String STATUS_DESCR)
    {
        this.STATUS_DESCR = STATUS_DESCR;
    }

    public String getINFO ()
    {
        return INFO;
    }

    public void setINFO (String INFO)
    {
        this.INFO = INFO;
    }

    public String getMPT_STATUS ()
    {
        return MPT_STATUS;
    }

    public void setMPT_STATUS (String MPT_STATUS)
    {
        this.MPT_STATUS = MPT_STATUS;
    }

    public String getSTATUS_KEY ()
    {
        return STATUS_KEY;
    }

    public void setSTATUS_KEY (String STATUS_KEY)
    {
        this.STATUS_KEY = STATUS_KEY;
    }

    public String getESCALATED ()
    {
        return ESCALATED;
    }

    public void setESCALATED (String ESCALATED)
    {
        this.ESCALATED = ESCALATED;
    }

    public String getESCALATION ()
    {
        return ESCALATION;
    }

    public void setESCALATION (String ESCALATION)
    {
        this.ESCALATION = ESCALATION;
    }

    public String getORG_LVL ()
    {
        return ORG_LVL;
    }

    public void setORG_LVL (String ORG_LVL)
    {
        this.ORG_LVL = ORG_LVL;
    }

    public String getPROCESS_TYPE ()
    {
        return PROCESS_TYPE;
    }

    public void setPROCESS_TYPE (String PROCESS_TYPE)
    {
        this.PROCESS_TYPE = PROCESS_TYPE;
    }

    public String getLAST_CHANGED_AT_SAP ()
    {
        return LAST_CHANGED_AT_SAP;
    }

    public void setLAST_CHANGED_AT_SAP (String LAST_CHANGED_AT_SAP)
    {
        this.LAST_CHANGED_AT_SAP = LAST_CHANGED_AT_SAP;
    }

    public String getINIT_RECP ()
    {
        return INIT_RECP;
    }

    public void setINIT_RECP (String INIT_RECP)
    {
        this.INIT_RECP = INIT_RECP;
    }

    public String getSERVICE_TEAM_TEXT ()
    {
        return SERVICE_TEAM_TEXT;
    }

    public void setSERVICE_TEAM_TEXT (String SERVICE_TEAM_TEXT)
    {
        this.SERVICE_TEAM_TEXT = SERVICE_TEAM_TEXT;
    }

    public String getMESSAGE_INSNO ()
    {
        return MESSAGE_INSNO;
    }

    public void setMESSAGE_INSNO (String MESSAGE_INSNO)
    {
        this.MESSAGE_INSNO = MESSAGE_INSNO;
    }

    public String getCSS_OBJECT_ID ()
    {
        return CSS_OBJECT_ID;
    }

    public void setCSS_OBJECT_ID (String CSS_OBJECT_ID)
    {
        this.CSS_OBJECT_ID = CSS_OBJECT_ID;
    }

    public String getWORK_PRIO ()
    {
        return WORK_PRIO;
    }

    public void setWORK_PRIO (String WORK_PRIO)
    {
        this.WORK_PRIO = WORK_PRIO;
    }

    public String getCUST_NO ()
    {
        return CUST_NO;
    }

    public void setCUST_NO (String CUST_NO)
    {
        this.CUST_NO = CUST_NO;
    }

    public String getWORK_PRIO_SORT ()
    {
        return WORK_PRIO_SORT;
    }

    public void setWORK_PRIO_SORT (String WORK_PRIO_SORT)
    {
        this.WORK_PRIO_SORT = WORK_PRIO_SORT;
    }

    public String getOBJECT_GUID ()
    {
        return OBJECT_GUID;
    }

    public void setOBJECT_GUID (String OBJECT_GUID)
    {
        this.OBJECT_GUID = OBJECT_GUID;
    }

    public String getORT_ACT_END ()
    {
        return ORT_ACT_END;
    }

    public void setORT_ACT_END (String ORT_ACT_END)
    {
        this.ORT_ACT_END = ORT_ACT_END;
    }

    public String getPROCESSOR_ID ()
    {
        return PROCESSOR_ID;
    }

    public void setPROCESSOR_ID (String PROCESSOR_ID)
    {
        this.PROCESSOR_ID = PROCESSOR_ID;
    }

    public String getURL_MESSAGE ()
    {
        return URL_MESSAGE;
    }

    public void setURL_MESSAGE (String URL_MESSAGE)
    {
        this.URL_MESSAGE = URL_MESSAGE;
    }

    @Override
    public String toString()
    {
        return "Class DATA [PROCESSING_ORG_TXT = "+PROCESSING_ORG_TXT+", MPT_EXCEEDED = "+MPT_EXCEEDED+", SCOPING_KEY = "+SCOPING_KEY+", MPT_USED = "+MPT_USED+", INIT_SEND = "+INIT_SEND+", OBJECT_ID = "+OBJECT_ID+", EMPL_RESP = "+EMPL_RESP+", MESSAGE_NO = "+MESSAGE_NO+", PROCESSOR = "+PROCESSOR+", REPORTER_ID = "+REPORTER_ID+", CHANGE_DATE = "+CHANGE_DATE+", MESSAGE_YEAR = "+MESSAGE_YEAR+", IRT_FUL = "+IRT_FUL+", ORT_PLAN_END = "+ORT_PLAN_END+", DESCRIPTION = "+DESCRIPTION+", IRT_STATUS = "+IRT_STATUS+", MPT_START = "+MPT_START+", QUEUE_NAME = "+QUEUE_NAME+", SOL_PLANNED = "+SOL_PLANNED+", IRT_USED = "+IRT_USED+", PRIORITY_DESCR = "+PRIORITY_DESCR+", IRT_EXPIRY = "+IRT_EXPIRY+", CUST_NAME = "+CUST_NAME+", IRT_START = "+IRT_START+", CREATE_DATE = "+CREATE_DATE+", SCOPING_DESCR = "+SCOPING_DESCR+", REPORTER_NAME = "+REPORTER_NAME+", SYSTEM_ID = "+SYSTEM_ID+", PROCESSING_ORG = "+PROCESSING_ORG+", READMARK = "+READMARK+", PROCESSOR_NAME = "+PROCESSOR_NAME+", CONFIRMATION_DATE = "+CONFIRMATION_DATE+", ORG_LVL_TEXT = "+ORG_LVL_TEXT+", CATEGORY = "+CATEGORY+", PRIORITY_KEY = "+PRIORITY_KEY+", MPT_EXPIRY = "+MPT_EXPIRY+", STATUS_DESCR = "+STATUS_DESCR+", INFO = "+INFO+", MPT_STATUS = "+MPT_STATUS+", STATUS_KEY = "+STATUS_KEY+", ESCALATED = "+ESCALATED+", ESCALATION = "+ESCALATION+", ORG_LVL = "+ORG_LVL+", PROCESS_TYPE = "+PROCESS_TYPE+", LAST_CHANGED_AT_SAP = "+LAST_CHANGED_AT_SAP+", INIT_RECP = "+INIT_RECP+", SERVICE_TEAM_TEXT = "+SERVICE_TEAM_TEXT+", MESSAGE_INSNO = "+MESSAGE_INSNO+", CSS_OBJECT_ID = "+CSS_OBJECT_ID+", WORK_PRIO = "+WORK_PRIO+", CUST_NO = "+CUST_NO+", WORK_PRIO_SORT = "+WORK_PRIO_SORT+", OBJECT_GUID = "+OBJECT_GUID+", ORT_ACT_END = "+ORT_ACT_END+", PROCESSOR_ID = "+PROCESSOR_ID+", URL_MESSAGE = "+URL_MESSAGE+"]";
    }

    public void printIRTObject() {
        IRT irt = new IRT(IRT_EXPIRY);
        System.out.println(irt);
    }

    // if the IRT shows 'OK' --> invalid
    // if the IRT shows traffic light --> valid
    public boolean hasValidIRT() {
        if (LAST_CHANGED_AT_SAP.equals("0")) {
            return true;
        }
        return false;
    }

    @Override
    public int compareTo(DATA data) {
        IRT thisIRT = new IRT(IRT_EXPIRY);
        IRT dataIRT = new IRT(data.IRT_EXPIRY);

        if (thisIRT.getYear() != dataIRT.getYear()) {
            return thisIRT.getYear() - dataIRT.getYear();
        } else if (thisIRT.getDate() != dataIRT.getDate()) {
            return thisIRT.getDate() - dataIRT.getDate();
        } else  if (thisIRT.getHour() != dataIRT.getHour()) {
            return thisIRT.getHour() - dataIRT.getHour();
        } else {
            return thisIRT.getMinute() - dataIRT.getMinute();
        }

    }
}
